# permissions for end users to view leases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lease-viewer-role
rules:
- apiGroups:
  - coredhcp.roob.re
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coredhcp.roob.re
  resources:
  - leases/status
  verbs:
  - get
