# permissions for end users to edit leases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lease-editor-role
rules:
- apiGroups:
  - coredhcp.roob.re
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coredhcp.roob.re
  resources:
  - leases/status
  verbs:
  - get
