# permissions for end users to view staticleases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: staticlease-viewer-role
rules:
- apiGroups:
  - coredhcp.roob.re
  resources:
  - staticleases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coredhcp.roob.re
  resources:
  - staticleases/status
  verbs:
  - get
