# permissions for end users to edit staticleases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: staticlease-editor-role
rules:
- apiGroups:
  - coredhcp.roob.re
  resources:
  - staticleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coredhcp.roob.re
  resources:
  - staticleases/status
  verbs:
  - get
